services:
  backend:
    environment:
      - branch
      - name
      - token
      - domain
      - supabasekey
    2342342 14319287349213479283477747893217490827439217  83490856902183466573281900szzgbn

      - supabaseurl
      - jwtpriv
    ports:
      - "8000:8000"
    build: ./Backend
  frontend:
    environment:
      - branch
      - VITE_DOMAIN
      - VITE_SUPABASE_URL
      - VITE_SUPABASE_KEY
    ports:
      - "80:80"
      - "3000:3000"
    build: 
      context: ./Frontend
      args:
      - VITE_DOMAIN=${VITE_DOMAIN}
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_KEY=${VITE_SUPABASE_KEY}
networks:
  default:
    name: backend
