services:
  backend:
    environment:
      - branch
      - name
      - token
      - domain
      - supabasekey
      - supabaseurl
      - jwtpriv
      - bigdatacloudkey
    build: ./Backend
  frontend:
    volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - branch
      - VITE_SUPABASE_URL
      - VITE_SUPABASE_KEY
    ports:
      # - "80:80"
      - "3000:80"
    build: 
      context: ./Frontend
      args:
      - VITE_DOMAIN=${VITE_DOMAIN}
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_KEY=${VITE_SUPABASE_KEY}
networks:
  default:
    name: backend
