name: ci

on:
  push:
    branches:
      - 'main'
      - 'beta'
      - 'dev'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to soerens registry
        uses: docker/login-action@v1 
        with:
          registry: docker.soerensserver.xyz
          username: ${{ secrets.dockerUser }}
          password: ${{ secrets.dockerPassword }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./Frontend
          build-args: |
            domain=${{ steps.extract_branch.outputs.branch }}backend.geobingo.io
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            docker.soerensserver.xyz/bingo-frontend-${{ steps.extract_branch.outputs.branch }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./Backend
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            docker.soerensserver.xyz/bingo-backend-${{ steps.extract_branch.outputs.branch }}



